apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-agrocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matriix00/argocd.git
    targetRevision: HEAD
    path: dev 
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy: 
    syncOptions:
    - CreateNamespace=true

    automated: 
      selfHeal: true
      prune: true   
